# Caduceus — 双蛇杖，赫尔墨斯的信使工具
# Hermes Agent 适配器 — 轮询采集与任务委托

import json
import logging
import os
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

from integrations.olympus import AgentAdapter, AgentRegistry

logger = logging.getLogger(__name__)


class HermesAdapter(AgentAdapter):
    """Hermes Agent 适配器

    Hermes 采用 Poll 机制：
    - Mnemos 轮询 Hermes 输出目录 ~/.hermes/sessions/ 采集信号
    - 蒸馏任务写入 ~/.hermes/inbox/ 等待 Hermes 处理
    """

    @property
    def name(self) -> str:
        return "hermes"

    @property
    def priority(self) -> int:
        return 2

    def is_available(self) -> bool:
        """检测 Hermes 是否安装"""
        hermes_dir = Path.home() / ".hermes"
        return hermes_dir.exists()

    def get_data_dir(self) -> Optional[Path]:
        return Path.home() / ".hermes"

    def on_session_start(self, working_dir: str, user_message: str = "") -> Dict:
        knowledge = self.inject_knowledge("general", context_text=user_message)
        # 同时发布到事件总线（Agent-agnostic 通信）
        try:
            from core.mnemos_bus import EventBus
            bus = EventBus()
            bus.publish("session.start", self.name, {
                "working_dir": working_dir,
                "user_message": user_message,
                "knowledge_loaded": knowledge.get("loaded", False),
            })
        except Exception:
            pass  # 事件总线失败不影响主流程
        return {"agent": self.name, "knowledge": knowledge}

    def on_session_end(self, working_dir: str, session_messages: List[Dict] = None) -> Dict:
        sid = None
        if session_messages:
            try:
                from core.kia.amphora import enqueue
                from datetime import datetime
                wd = working_dir or os.getcwd()
                dir_hash = __import__('hashlib').md5(wd.encode()).hexdigest()[:8]
                ts = datetime.now().strftime("%Y%m%d-%H%M%S")
                sid = f"hermes:{dir_hash}:{ts}"
                enqueue(
                    session_id=sid,
                    messages=session_messages,
                    meta={"source": "hermes", "working_dir": wd}
                )
            except Exception as e:
                logger.warning(f"Hermes 蒸馏入队失败: {e}")
        # 同时发布到事件总线
        try:
            from core.mnemos_bus import EventBus
            bus = EventBus()
            bus.publish("session.end", self.name, {
                "working_dir": working_dir,
                "session_id": sid,
                "messages": session_messages or [],
                "meta": {"source": self.name, "working_dir": working_dir or os.getcwd()},
            })
        except Exception:
            pass
        return {"saved": True, "distill_task_id": sid}

    def install_hooks(self) -> bool:
        """安装 Hermes 的 session hooks

        生成配置文件和 wrapper 脚本，实现 session 事件的自动上报。
        """
        try:
            hermes_dir = self.get_data_dir()
            hermes_dir.mkdir(parents=True, exist_ok=True)

            # 1. 生成 wrapper 脚本
            wrapper_path = hermes_dir / "mnemos_wrapper.py"
            wrapper_content = self._generate_wrapper_script()
            wrapper_path.write_text(wrapper_content, encoding="utf-8")

            # 2. 写入配置文件
            config_path = hermes_dir / "mnemos_config.toml"
            config_content = f"""# Mnemos integration for Hermes
# Auto-generated by Mnemos — do not edit manually

[mnemos]
enabled = true
wrapper = "{wrapper_path}"

[callbacks]
session_start = "python3 {wrapper_path} --session-start"
session_end = "python3 {wrapper_path} --session-end"

[paths]
sessions = "{hermes_dir / 'sessions'}"
inbox = "{hermes_dir / 'inbox'}"
"""
            config_path.write_text(config_content, encoding="utf-8")

            # 3. 生成安装说明
            readme_path = hermes_dir / "mnemos_install.md"
            readme_content = f"""# Mnemos 集成安装说明

## 已自动生成的文件

1. **Wrapper 脚本**: `{wrapper_path}`
   - 接收 Hermes 的 session 事件并写入 Mnemos 事件总线

2. **配置文件**: `{config_path}`
   - 包含 callbacks 和路径配置

3. **本说明**: `{readme_path}`

## 手动步骤

在 Hermes 的配置中引用上述 callbacks：

```toml
[mnemos]
enabled = true
session_start = "python3 {wrapper_path} --session-start"
session_end = "python3 {wrapper_path} --session-end"
```

## 测试

```bash
python3 {wrapper_path} --session-start --working-dir $(pwd) --user-message "test"
```
"""
            readme_path.write_text(readme_content, encoding="utf-8")

            logger.info(f"[Caduceus] Hermes hooks 已安装到 {hermes_dir}")
            return True
        except Exception as e:
            logger.warning(f"[Caduceus] 安装 Hermes hooks 失败: {e}")
            return False

    def _generate_wrapper_script(self) -> str:
        """生成 Hermes wrapper 脚本"""
        return '''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Mnemos-Hermes Wrapper
接收 Hermes 的 session 事件，写入 Mnemos 事件总线
"""

import sys
import os
import argparse
from pathlib import Path

# 确保能找到 Mnemos 模块
script_dir = Path(__file__).parent
sys.path.insert(0, str(script_dir.parent.parent))

from core.mnemos_bus import EventBus


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--session-start", action="store_true")
    parser.add_argument("--session-end", action="store_true")
    parser.add_argument("--working-dir", default=os.getcwd())
    parser.add_argument("--user-message", default="")
    args = parser.parse_args()

    bus = EventBus()

    if args.session_start:
        bus.publish("session.start", "hermes", {
            "working_dir": args.working_dir,
            "user_message": args.user_message,
        })
        print("[Mnemos] session.start 事件已发布")
    elif args.session_end:
        bus.publish("session.end", "hermes", {
            "working_dir": args.working_dir,
            "messages": [],
            "meta": {"source": "hermes", "working_dir": args.working_dir},
        })
        print("[Mnemos] session.end 事件已发布")


if __name__ == "__main__":
    main()
'''

    def collect_signals(self, days: int = 7) -> List[Dict]:
        """轮询 Hermes 输出目录采集信号"""
        signals = []
        sessions_dir = self.get_data_dir() / "sessions"
        if not sessions_dir.exists():
            return signals

        from datetime import datetime, timedelta
        cutoff = datetime.now() - timedelta(days=days)

        for json_file in sorted(sessions_dir.glob("*.json"), reverse=True):
            try:
                data = json.loads(json_file.read_text(encoding="utf-8"))
                ts_str = data.get("timestamp", "")
                if ts_str:
                    ts = datetime.fromisoformat(ts_str.replace("Z", "+00:00"))
                    if ts < cutoff:
                        break
                signals.append({
                    "source": "hermes",
                    "session_id": data.get("session_id"),
                    "timestamp": ts_str,
                    "task_type": data.get("task_type", "unknown"),
                    "raw": data,
                })
            except Exception as e:
                logger.warning(f"解析 Hermes 会话失败 {json_file}: {e}")
                continue

        return signals

    def inject_knowledge(self, task_type: str, subtype: str = "", context_text: str = "") -> Dict:
        from core.kia.prophasis import PreFlightInjector
        from core.kia.kairos import TimeWindow, TimeWindowType
        injector = PreFlightInjector()
        time_window = TimeWindow(window=TimeWindowType.IMMEDIATE, days_until=0)
        knowledge = injector.inject(task_type, subtype, time_window, context_text)
        if not knowledge:
            return {"loaded": False}
        return {
            "loaded": True,
            "task_type": knowledge.task_type,
            "checklist": [c.item for c in knowledge.checklist],
        }

    def delegate_distillation(self, task_path: Path, output_path: Path) -> bool:
        """委托 Hermes 执行蒸馏

        策略：将任务写入 ~/.hermes/inbox/，Hermes 轮询处理。
        同时写入通知标记文件，提示 Hermes 有新任务。
        """
        try:
            task = json.loads(task_path.read_text(encoding="utf-8"))
            inbox_dir = self.get_data_dir() / "inbox"
            inbox_dir.mkdir(parents=True, exist_ok=True)
            task_file = inbox_dir / f"mnemos_distill_{task.get('session_id', 'unknown')}.json"
            task["output_path"] = str(output_path)
            task["type"] = "distillation"
            task_file.write_text(json.dumps(task, ensure_ascii=False, indent=2), encoding="utf-8")
            # 写入通知标记
            notify_file = inbox_dir / ".mnemos_notify"
            notify_content = f"""# Mnemos 蒸馏任务通知

**Agent**: hermes
**时间**: {datetime.now().isoformat()}
**待处理任务**: {task.get('session_id', 'unknown')}
**任务文件**: {task_file}
**输出路径**: {output_path}

Hermes 请检查 inbox 目录处理此任务。
"""
            notify_file.write_text(notify_content, encoding="utf-8")
            # 写入输出占位符（Agent 会覆盖）
            output_path.parent.mkdir(parents=True, exist_ok=True)
            # 构建完整 prompt 文件（供 Hermes 直接阅读）
            prompt_content = self._build_distill_prompt(task)
            prompt_file = inbox_dir / f"mnemos_prompt_{task.get('session_id', 'unknown')}.md"
            prompt_file.write_text(prompt_content, encoding="utf-8")

            placeholder = (
                f"<!-- MNEMOS_DISTILL_TASK: {task.get('session_id')} -->\n"
                f"<!-- 输出格式要求：\n"
                f"  1. 必须是有效的 JSON 对象\n"
                f"  2. 顶层字段：judgment (knowledge/skill/skip), fragments (数组)\n"
                f"  3. 每个 fragment 包含：form, title, frontmatter, background, core_content, boundaries, anti_patterns, related_concepts\n"
                f"  4. 完整 prompt 和格式要求见：{prompt_file}\n"
                f"-->\n"
                f"<!-- Hermes 请阅读 {prompt_file} 并生成蒸馏结果 -->\n"
            )
            output_path.write_text(placeholder, encoding="utf-8")
            return True
        except Exception as e:
            logger.warning(f"委托 Hermes 蒸馏失败: {e}")
            return False

    def _build_distill_prompt(self, task: Dict) -> str:
        meta = task.get("meta", {})
        if meta.get("full_prompt"):
            return meta["full_prompt"]
        try:
            from core.hephaestus.distillation_prompts import DISTILLATION_PROMPT
            from core.hephaestus.distillation_engine import build_session_text

            messages = task.get("messages", [])
            session_text = build_session_text(messages)
            if not session_text:
                return self._build_fallback_prompt(task)
            return DISTILLATION_PROMPT.replace("{session_content}", session_text)
        except Exception as e:
            logger.warning(f"构建完整蒸馏 prompt 失败，使用回退: {e}")
            return self._build_fallback_prompt(task)

    def _build_fallback_prompt(self, task: Dict) -> str:
        meta = task.get("meta", {})
        messages = task.get("messages", [])
        lines = [
            "# Mnemos 蒸馏任务",
            "",
            f"**Session ID**: {task.get('session_id', 'unknown')}",
            f"**来源**: {meta.get('source', 'unknown')}",
            f"**工作目录**: {meta.get('working_dir', '')}",
            "",
            "## 指令",
            "请对以下对话进行蒸馏，提取核心知识、经验教训和可复用的模式。",
            "输出严格 JSON 格式（见 distillation_prompts.py 完整要求）。",
            "",
            "## 原始对话",
            "",
        ]
        for msg in messages:
            role = msg.get("role", "unknown")
            content = msg.get("content", "")
            lines.append(f"### {role}")
            lines.append(content)
            lines.append("")
        return "\n".join(lines)


AgentRegistry.register(HermesAdapter)
