# Auto-generated by scripts/audit_vulture_whitelist.py
# Add reflection-aware # noqa annotations in source instead of growing this file.
#
# Review contract (K-09):
# - CLI/daemon dynamic dispatch, pytest fixtures/mock helpers, sqlite row_factory,
#   and DTO/dataclass contract fields are retention categories, not deletion
#   evidence by themselves.
# - Prefer a targeted source `# noqa` or a precise audit rule for these cases;
#   only keep them here when source suppression would be noisier than a whitelist.
