"""Unit tests for core.cognitive.sources.SourceReader."""

import pytest

from core.cognitive.sources import (
    CanonicalRawUnavailable,
    ContentTier,
    SourceItem,
    SourceReader,
)


@pytest.fixture
def wiki_root(tmp_path):
    """Create a temporary wiki directory with categorized markdown files."""
    wiki = tmp_path / "wiki"

    # User-generated content
    user_dir = wiki / "02-Projects"
    user_dir.mkdir(parents=True)
    (user_dir / "project-a.md").write_text(
        "---\ndate: 2026-06-01\nsource: user\n---\n\nI decided to refactor the codebase.",
        encoding="utf-8",
    )

    # External quoted content
    external_dir = wiki / "07-Shadow"
    external_dir.mkdir(parents=True)
    (external_dir / "book-quote.md").write_text(
        "---\ndate: 2026-06-02\nsource_type: book\n---\n\nA quote from a book about habits.",
        encoding="utf-8",
    )

    # System-generated content
    system_dir = wiki / "08-Reminders"
    system_dir.mkdir(parents=True)
    (system_dir / "daily-reminder.md").write_text(
        "---\ndate: 2026-06-03\nsource: system\n---\n\nDaily reminder generated by the system.",
        encoding="utf-8",
    )

    # Auto-updated dashboard
    dashboard_dir = wiki / "99-Reports"
    dashboard_dir.mkdir(parents=True)
    (dashboard_dir / "dashboard.md").write_text(
        "---\ndate: 2026-06-04\nauto_updated: true\nmnemos_type: dashboard\n---\n\nWeekly dashboard.",  # noqa: E501
        encoding="utf-8",
    )

    # Cognitive-layer projections that must not be fed back as input
    obs_dir = wiki / "L3-Observations"
    obs_dir.mkdir(parents=True)
    (obs_dir / "attention.md").write_text(
        "---\ndate: 2026-06-05\n---\n\n# Attention Observation\n\nAI: 42 mentions.",
        encoding="utf-8",
    )

    # Index file (should be skipped)
    (user_dir / "index.md").write_text("---\n---\n\nIndex page.", encoding="utf-8")

    return wiki


@pytest.fixture
def reader(wiki_root):
    return SourceReader(wiki_dir=str(wiki_root))


class TestSourceReaderContentTierFiltering:
    """Tests for SourceReader content-tier classification."""

    def test_user_generated_is_included(self, reader, wiki_root):
        items = list(reader.read_all())
        paths = {item.file_path for item in items}
        assert str(wiki_root / "02-Projects" / "project-a.md") in paths

    def test_external_quoted_is_included_with_tier(self, reader, wiki_root):
        items = list(reader.read_all())
        external = [item for item in items if "book-quote" in item.file_path]
        assert len(external) == 1
        assert external[0].content_tier == ContentTier.EXTERNAL_QUOTED

    def test_system_generated_is_excluded(self, reader, wiki_root):
        items = list(reader.read_all())
        paths = {item.file_path for item in items}
        assert str(wiki_root / "08-Reminders" / "daily-reminder.md") not in paths
        assert str(wiki_root / "99-Reports" / "dashboard.md") not in paths
        assert str(wiki_root / "L3-Observations" / "attention.md") not in paths

    def test_index_md_is_skipped(self, reader, wiki_root):
        items = list(reader.read_all())
        paths = {item.file_path for item in items}
        assert str(wiki_root / "02-Projects" / "index.md") not in paths

    def test_wiki_content_source_inferred(self, reader):
        items = list(reader.read_all())
        project_item = [item for item in items if "project-a" in item.file_path][0]
        assert project_item.frontmatter.get("source") == "user"
        assert project_item.timestamp is not None
        assert project_item.timestamp.tzinfo is not None

    def test_non_scalar_frontmatter_identity_is_not_used_as_a_source_key(self):
        item = SourceItem(
            source_type="wiki",
            file_path="/wiki/non-scalar.md",
            content="metadata must remain typed",
            frontmatter={"session_id": ["bad"], "source": ["bad"]},
        )

        assert item.session_id is None
        assert item.source_agent is None


class TestSourceReaderGetStats:
    """Tests for SourceReader.get_stats."""

    def test_get_stats_counts(self, reader, wiki_root):
        stats = reader.get_stats()

        assert stats["raw_items"] == 0
        # External quoted is treated as excluded, so only user-generated counts as wiki file.
        assert stats["wiki_files"] == 1
        assert stats["total_items"] == 1
        assert stats["excluded_system"] == 3
        assert stats["excluded_external"] == 1
        assert stats["raw_projection_dir"] is None
        assert stats["wiki_dir"] == str(wiki_root)

        tier_breakdown = stats["tier_breakdown"]
        assert tier_breakdown.get(ContentTier.USER_GENERATED.value) == 1
        assert tier_breakdown.get(ContentTier.EXTERNAL_QUOTED.value) == 1
        assert tier_breakdown.get(ContentTier.SYSTEM_GENERATED.value) == 3

    def test_get_stats_with_missing_wiki_dir(self, tmp_path):
        reader = SourceReader(wiki_dir=str(tmp_path / "does-not-exist"))
        stats = reader.get_stats()

        assert stats["raw_items"] == 0
        assert stats["wiki_files"] == 0
        assert stats["total_items"] == 0
        assert stats["excluded_system"] == 0
        assert stats["excluded_external"] == 0

    def test_projection_files_are_not_counted_as_raw_items(self, tmp_path):
        raw = tmp_path / "raw"
        raw.mkdir()
        (raw / "session.md").write_text("content", encoding="utf-8")

        reader = SourceReader(raw_projection_dir=str(raw))
        stats = reader.get_stats()

        assert stats["raw_items"] == 0
        assert stats["raw_projection_files"] == 1
        assert stats["wiki_files"] == 0
        assert stats["total_items"] == 0
        with pytest.raises(
            CanonicalRawUnavailable,
            match="canonical raw database was not configured",
        ):
            list(reader.read_all())


class TestSourceReaderLimits:
    def test_read_since_respects_max_items(self, tmp_path):
        """max_items 应限制返回数量"""
        wiki = tmp_path / "wiki"
        wiki.mkdir()
        for i in range(10):
            path = wiki / f"note-{i}.md"
            path.write_text(f"---\ndate: 2026-06-{i + 1:02d}\n---\ncontent {i}", encoding="utf-8")

        reader = SourceReader(wiki_dir=str(wiki))
        items = list(reader.read_since(max_items=3))
        assert len(items) == 3

    def test_read_since_clamps_lookback(self, tmp_path):
        """max_lookback_hours 应限制 since 不能太旧"""
        import os
        import time

        wiki = tmp_path / "wiki"
        wiki.mkdir()
        path = wiki / "old.md"
        path.write_text("---\ndate: 2026-01-01\n---\nold", encoding="utf-8")
        # 把文件 mtime 设到 30 天前
        old_mtime = time.time() - 30 * 86400
        os.utime(path, (old_mtime, old_mtime))

        reader = SourceReader(wiki_dir=str(wiki))
        old_since = __import__("datetime").datetime(2026, 1, 1, tzinfo=__import__("datetime").timezone.utc)
        items = list(reader.read_since(since=old_since, max_lookback_hours=24))
        # since 被 clamp 到 24h 前，而文件在 30 天前，所以不应返回
        assert len(items) == 0
