"""Immutable object schemas and field-denominator contracts."""

from __future__ import annotations

import re
from types import MappingProxyType
from typing import Mapping

from core.cognition_episode_contract import (
    COGNITION_EPISODE_FIELDS,
    COGNITION_EPISODE_SCHEMA_VERSION,
    COGNITION_EPISODE_V2_FIELDS,
)
from core.cognitive.training_contract import (
    TRAINING_ADMISSION_SCHEMA_VERSION,
    TRAINING_RUN_SCHEMA_VERSION,
)

COGNITIVE_STATE_CONTRACT_VERSION = "mnemos.cognitive_state_contract.v1"
VALUE_PRECEDENCE_CONTRACT = "mnemos.value_precedence.v1"
FIXED_VALUE_PRECEDENCE = (
    "safety_permission_privacy",
    "explicit_user_goal",
    "project_constraint",
    "scoped_preference",
    "cost_convenience",
)
_VALUE_AUTHORITY_BY_CATEGORY = {
    "safety_permission_privacy": frozenset({"system_policy", "explicit_user", "project_contract"}),
    "explicit_user_goal": frozenset({"explicit_user"}),
    "project_constraint": frozenset({"project_contract", "system_policy"}),
    "scoped_preference": frozenset({"explicit_user", "project_contract"}),
    "cost_convenience": frozenset({"system_policy", "explicit_user", "project_contract"}),
}
_SHA256_PATTERN = re.compile(r"sha256:[0-9a-f]{64}\Z")
_OMISSION_ID_PATTERN = re.compile(r"omission:[0-9a-f]{32}\Z")

COGNITIVE_OBJECT_SCHEMA_VERSIONS: Mapping[str, str] = MappingProxyType(
    {
        "cognition_episode": COGNITION_EPISODE_SCHEMA_VERSION,
        "belief_revision": "mnemos.belief_revision.v1",
        "cognitive_state_snapshot": "mnemos.cognitive_state_snapshot.v2",
        "decision_trace": "mnemos.decision_trace.v1",
        "prediction_record": "mnemos.prediction_record.v1",
        "value_context": "mnemos.value_context.v1",
        "calibration_record": "mnemos.calibration_record.v1",
        "user_reaction_event": "mnemos.user_reaction_event.v1",
        "feedback_attribution_record": "mnemos.feedback_attribution_record.v1",
        "outcome_measurement": "mnemos.outcome_measurement.v1",
        "cognitive_update_receipt": "mnemos.cognitive_update_receipt.v1",
        "training_admission_record": TRAINING_ADMISSION_SCHEMA_VERSION,
        "training_run_record": TRAINING_RUN_SCHEMA_VERSION,
    }
)
COGNITIVE_OBJECT_TYPES = frozenset(COGNITIVE_OBJECT_SCHEMA_VERSIONS)

_REQUIRED_PAYLOAD_FIELDS: Mapping[str, tuple[str, ...]] = MappingProxyType(
    {
        "cognition_episode": (
            "schema_version",
            "cognition_context_hash",
            "input_spec_hash",
            "extraction_output_hash",
            "source_agent",
            "source_session_id",
            "source_event_ids",
            "raw_completeness",
            "loss_contract",
            "source_spans",
            "artifact_catalog_hash",
            "source_authority_catalog_hash",
            "source_authority_catalog",
            "artifact_catalog",
            "acl",
            "purpose",
            "retention_policy",
            *COGNITION_EPISODE_V2_FIELDS,
            *COGNITION_EPISODE_FIELDS,
        ),
        "belief_revision": (
            "schema_version",
            "belief_id",
            "claim_id",
            "claim",
            "claim_kind",
            "stance",
            "supporting_evidence",
            "opposing_evidence",
            "withdrawn_evidence",
            "confidence_method",
            "confidence",
            "confidence_evidence",
            "uncertainty",
            "valid_from",
            "valid_until",
            "invalidation_conditions",
            "admission_refs",
            "supersedes_revision_id",
            "correction_of_revision_id",
        ),
        "cognitive_state_snapshot": (
            "schema_version",
            "snapshot_id",
            "snapshot_hash",
            "task",
            "goal",
            "constraints",
            "scope",
            "source_completeness",
            "evidence_refs",
            "active_belief_refs",
            "profile_revision_refs",
            "value_context_revision_id",
            "value_context_hash",
            "source_authority_catalog_hash",
            "policy_revision_refs",
            "consumed_state",
            "head_preconditions",
            "state_hash",
        ),
        "decision_trace": (
            "schema_version",
            "decision_id",
            "decision_state",
            "supersedes_decision_revision_ids",
            "task",
            "goal",
            "constraints",
            "snapshot_id",
            "snapshot_revision_id",
            "snapshot_hash",
            "value_context_id",
            "value_context_revision_id",
            "value_context_hash",
            "source_authority_catalog_hash",
            "belief_revision_refs",
            "profile_revision_refs",
            "policy_revision_refs",
            "candidates",
            "rejected_reasons",
            "selection",
            "model_spec",
            "tool_specs",
            "prompt_spec",
            "expected_outcomes",
            "prediction_refs",
            "evaluation_window",
            "approval",
            "action_specs",
            "action_refs",
            "effect_refs",
        ),
        "prediction_record": (
            "schema_version",
            "prediction_id",
            "revision_state",
            "prediction_plan_hash",
            "prediction_input_hash",
            "supersedes_revision_id",
            "correction_of_revision_id",
            "subject",
            "scope",
            "source_snapshot",
            "decision_ref",
            "action_ref",
            "delivery_ref",
            "route_disposition",
            "prediction_kind",
            "metric",
            "confidence",
            "evaluation_window",
            "causal_assumptions",
            "exposure",
            "outcome_ref",
            "attribution",
            "terminal",
            "error",
            "calibration",
        ),
        "value_context": (
            "schema_version",
            "value_context_id",
            "scope",
            "valid_from",
            "valid_until",
            "precedence_contract",
            "source_authority_catalog_hash",
            "source_authority_catalog",
            "items",
            "conflicts",
            "disposition",
            "consumed_refs",
            "consumed_refs_hash",
            "supersedes_revision_id",
            "user_goal",
            "project_constraints",
            "safety_constraints",
            "privacy_constraints",
            "cost_constraints",
            "reversibility",
            "precedence",
        ),
        "calibration_record": (
            "schema_version",
            "observation_id",
            "prior",
            "posterior",
            "overall_verdict",
            "validator_version",
            "validator_spec_hash",
            "validator_code_hashes",
            "independent_evidence_clusters",
            "supporting_evidence",
            "counter_evidence",
            "calculation_input_hash",
            "input_snapshot",
            "valid_from",
            "valid_until",
            "source_span_ids",
            "omission_receipts",
            "derived_source_double_count",
            "derived_members_deduplicated",
            "validations",
        ),
        "user_reaction_event": (
            "schema_version",
            "reaction_id",
            "revision_state",
            "reaction_input_hash",
            "source_event_ref",
            "observed_at",
            "recorded_at",
            "supersedes_event_id",
            "correction_of_event_id",
            "delivery_ref",
            "principal_ref",
            "scope",
            "source_channel",
            "authority_class",
            "subject_ref",
            "decision_ref",
            "prediction_ref",
            "action_ref",
            "display_ref",
            "search_ref",
            "interaction",
            "evidence",
            "observation_window",
            "exposure",
            "competing_causes",
            "source_completeness",
            "attribution",
            "downstream",
            "correction",
        ),
        "feedback_attribution_record": (
            "schema_version",
            "attribution_id",
            "revision_state",
            "subject_ref",
            "scope",
            "reaction_refs",
            "outcome_refs",
            "input_set_hash",
            "independence_keys",
            "method",
            "evidence_class",
            "materiality",
            "competing_causes",
            "uncertainty",
            "disposition",
            "post_neutralization_disposition",
            "target_registry",
            "target_dispositions",
            "supersedes_revision_id",
            "correction_of_revision_id",
        ),
        "outcome_measurement": (
            "schema_version",
            "outcome_id",
            "prediction_ref",
            "decision_ref",
            "action_ref",
            "delivery_ref",
            "presentation_ref",
            "subject",
            "metric",
            "baseline",
            "observed_value",
            "observation_window",
            "maturity",
            "raw_evidence",
            "measurement_method",
            "uncertainty",
            "attribution",
            "source_authority",
            "supersedes_revision_id",
            "correction_of_revision_id",
        ),
        "cognitive_update_receipt": (
            "input_refs",
            "attribution",
            "target_command_ref",
            "before_hash",
            "after_hash",
            "effect_receipt_ref",
        ),
        "training_admission_record": (
            "schema_version",
            "admission_id",
            "revision_state",
            "input_set_hash",
            "supersedes_revision_id",
            "correction_of_revision_id",
            "training_evidence_ref",
            "prediction_ref",
            "prediction_terminal_ref",
            "outcome_ref",
            "decision_ref",
            "material_effect_ref",
            "delivery_ref",
            "subject",
            "scope",
            "principal_ref",
            "temporal_proof",
            "authority_proof",
            "feature_snapshot",
            "label",
            "evidence_quality",
            "dataset_assignment",
            "lifecycle_state",
            "target_effect_refs",
        ),
        "training_run_record": (
            "schema_version",
            "run_id",
            "run_input_hash",
            "dimension",
            "algorithm",
            "admission_refs",
            "dataset_manifest",
            "fit_input_hash",
            "validation_report",
            "holdout_report",
            "parent_model_ref",
            "model_artifact",
            "state",
            "material_effect_refs",
            "projection_receipt_ref",
            "supersedes_revision_id",
            "rebuild_of_revision_id",
        ),
    }
)

_SEQUENCE_FIELDS = frozenset(
    {
        "constraints",
        "facts",
        "hypotheses",
        "causal_links",
        "alternatives",
        "tradeoffs",
        "decisions",
        "actions",
        "outcomes",
        "corrections",
        "supporting_evidence",
        "opposing_evidence",
        "withdrawn_evidence",
        "confidence_evidence",
        "invalidation_conditions",
        "evidence_refs",
        "active_belief_refs",
        "profile_revision_refs",
        "policy_revision_refs",
        "belief_revision_refs",
        "candidates",
        "rejected_reasons",
        "expected_outcomes",
        "prediction_refs",
        "action_refs",
        "effect_refs",
        "supersedes_decision_revision_ids",
        "tool_specs",
        "action_specs",
        "items",
        "conflicts",
        "consumed_refs",
        "consumed_state",
        "head_preconditions",
        "project_constraints",
        "safety_constraints",
        "privacy_constraints",
        "cost_constraints",
        "precedence",
        "independent_evidence_clusters",
        "supporting_evidence",
        "counter_evidence",
        "source_span_ids",
        "omission_receipts",
        "validations",
        "confounders",
        "competing_causes",
        "reaction_refs",
        "outcome_refs",
        "independence_keys",
        "target_dispositions",
        "input_refs",
    }
)
