"""Shared Persona signal-store operating constants."""

SIGNAL_STORE_DURATION_BUCKET_QUARTER_DAYS = 90
SIGNAL_STORE_GET_SIGNAL_STATS_DAYS = 30
SIGNAL_STORE_GET_SIGNAL_HEALTH_DAYS = 30
CORE = 30
SIGNAL_STORE_GET_SIGNAL_PROJECTS_DAYS = 90
SIGNAL_STORE_GET_PROJECT_ISOLATED_SIGNALS_PROJECT_DIR_DAYS = 90
DURATION_BUCKET_WEEK_DAYS = 7
SIGNAL_STORE_SQLITE_TIMEOUT_SECONDS = 2.0
SIGNAL_STORE_BUSY_TIMEOUT_MS = 2_000
