#!/usr/bin/env python3
"""
Archive garbage wiki pages generated by wiki_builder.py (rule-based generation).

识别特征：frontmatter 中含有 `source_agent:`（英文键名）
保留文件：frontmatter 中含有 `来源:`（中文键名）→ distillation_engine.py 产出
"""

import shutil
from datetime import datetime

# [P1-FIX] 使用 get_config() 获取路径，避免硬编码
from core.config import get_config

_WIKI_DIR = get_config().wiki_dir
INBOX = _WIKI_DIR / "00-Inbox"
ARCHIVE = _WIKI_DIR / "06-Retrospectives" / f"garbage_{datetime.now().strftime('%Y%m%d')}"


def is_wiki_builder_garbage(content: str) -> bool:
    """判断是否为 wiki_builder.py 生成的低质量页面"""
    # 必须匹配英文 frontmatter 格式（wiki_builder.py 特征）
    if "source_agent:" in content and "type:" in content:
        # 排除 distillation_engine.py 的中文格式
        if "来源:" in content:
            return False
        return True
    return False


def main():
    ARCHIVE.mkdir(parents=True, exist_ok=True)

    files = list(INBOX.glob("*.md"))
    garbage = []
    keep = []

    for f in files:
        content = f.read_text(encoding="utf-8", errors="replace")
        if is_wiki_builder_garbage(content):
            garbage.append(f)
        else:
            keep.append(f)

    print(f"Total: {len(files)} files")
    print(f"Garbage (wiki_builder): {len(garbage)}")
    print(f"Keep (distillation_engine): {len(keep)}")
    print()

    if not garbage:
        print("No garbage found.")
        return

    # Move garbage to archive
    for f in garbage:
        dest = ARCHIVE / f.name
        shutil.move(str(f), str(dest))
        print(f"  [MOVED] {f.name}")

    print(f"\nArchived {len(garbage)} files to {ARCHIVE}")


if __name__ == "__main__":
    main()
