#!/usr/bin/env python3
"""Reflection-aware vulture whitelist audit.

This script runs vulture without the project whitelist and classifies the
findings.  By default it is read-only and reports the source suppressions
(``# noqa``) plus whitelist body changes it would make.  Passing ``--apply``
performs those changes for symbols that are used dynamically (fixtures, mock
attributes, sqlite3 row_factory assignments, etc.).  The remaining unresolved
findings are written back to ``vulture_whitelist.py`` only when the whitelist
body changes.

Safe actions performed with ``--apply``:
- add ``# noqa`` to ``*.row_factory`` sqlite3 assignments
- add ``# noqa`` to common pytest fixture / mock helper patterns
- add ``# noqa`` to known reflection-only attributes (``_sanitize``, etc.)
- add ``# noqa`` to interface/override methods reported as unused

Everything else is kept in the whitelist so a human can review it.
Do not delete CLI/daemon dispatch functions, pytest fixtures, sqlite
``row_factory`` assignments, or DTO/dataclass contract fields solely because
Vulture cannot see their dynamic consumers.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Set, Tuple

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_WHITELIST = PROJECT_ROOT / "vulture_whitelist.py"
WHITELIST_HEADER: Tuple[str, ...] = (
    "# Auto-generated by scripts/audit_vulture_whitelist.py",
    "# Add reflection-aware # noqa annotations in source instead of growing this file.",
    "",
)

# Patterns are matched against the *symbol* part of a whitelist entry, e.g.
# "_.row_factory", "monkeypatch_config", "_patch_get_config".
NOQA_PATTERNS: Tuple[str, ...] = (
    # sqlite3 row_factory is set for side effects; vulture sees no read.
    "_.row_factory",
    # Test helpers that are consumed dynamically by pytest / mock.patch.
    "monkeypatch_config",
    "mock_sklearn",
    "fake_kia_modules",
    "mock_active",
    "_block_event_bus_leakage",
    "_reset_distillation_pause_state",
    "sample_user_options",
    "sample_epub_file",
    "tmp_db_conn",
    "reset_singletons",
    "_windows_sqlite_cleanup",
    "_isolate_eventbus",
    "reset_config_singleton",
    "reset_default_pool",
    "clear_env_keys",
    "reset_delphi_singletons",
    "reset_registry",
    "reset_signal_store_singleton",
    "patch_config_for_freshness",
    "clean_llm_env",
    "auto_guard_files",
    # Fixtures / helpers with dynamic usage.
    "MinimalAdapter",
    "pytestmark",
    "_patch_et_get_config",
    "_patch_im_get_config",
    "_patch_get_config_for_scoring_v2_tests",
    "_patch_scorers_and_bus",
    "_patch_scorers",
    # Attribute assignments read via getattr/mock patching.
    "_._sanitize",
    "_.ai_expansion",
    "_._mock_slow_ops",
    "_.__enter__",
    "_.__exit__",
    "_._page_map",
    "_._embeddings",
    "_._noise_filter",
    "_._value_prejudgment",
    "_._feedback_loop",
    "_._fragment_merger",
    # Interface / override methods consumed through polymorphism.
    "_.get_session_state",
)

WHITELIST_LINE_RE = re.compile(
    r"^(?P<symbol>\S.*?)\s+#\s+unused\s+(?P<kind>\w+)\s+\((?P<path>[^:]+):(?P<line>\d+)\)$"
)


@dataclass(frozen=True)
class AuditResult:
    handled: int
    remaining: int
    source_edits: int
    whitelist_body_removed: int
    whitelist_written: bool
    whitelist_header_changed: bool
    dry_run: bool


def parse_whitelist(path: Path) -> List[Dict[str, Any]]:
    """Parse the whitelist file into structured entries."""
    entries: List[Dict[str, Any]] = []
    if not path.exists():
        return entries
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        m = WHITELIST_LINE_RE.match(raw.rstrip())
        if not m:
            # Preserve malformed lines by keeping them verbatim later.
            entries.append({"raw": raw})
            continue
        entries.append(
            {
                "symbol": m.group("symbol").strip(),
                "kind": m.group("kind"),
                "path": PROJECT_ROOT / m.group("path"),
                "line": int(m.group("line")),
                "raw": raw,
            }
        )
    return entries


def _matches(symbol: str, patterns: Iterable[str]) -> bool:
    for pat in patterns:
        # Exact match or glob-style prefix/suffix wildcard.
        if pat.startswith("*") and pat.endswith("*"):
            if pat[1:-1] in symbol:
                return True
        elif pat.startswith("*"):
            if symbol.endswith(pat[1:]):
                return True
        elif pat.endswith("*"):
            if symbol.startswith(pat[:-1]):
                return True
        elif symbol == pat:
            return True
    return False


def _line_needs_noqa(file_path: Path, line_number: int) -> bool:
    if not file_path.exists():
        return False
    lines = file_path.read_text(encoding="utf-8").splitlines()
    if line_number < 1 or line_number > len(lines):
        return False
    return "# noqa" not in lines[line_number - 1]


def _add_noqa(file_path: Path, line_number: int) -> bool:
    """Add ``# noqa`` to the given 1-based line if it is not already present."""
    text = file_path.read_text(encoding="utf-8")
    lines = text.splitlines(keepends=True)
    if line_number < 1 or line_number > len(lines):
        return False
    idx = line_number - 1
    original = lines[idx]
    stripped = original.rstrip("\n\r")
    if "# noqa" in stripped:
        return False
    # Append noqa before the newline, preserving existing trailing comment.
    lines[idx] = stripped + "  # noqa\n"
    file_path.write_text("".join(lines), encoding="utf-8")
    return True


def audit(
    whitelist_path: Path = DEFAULT_WHITELIST,
    dry_run: bool = True,
) -> AuditResult:
    """Run the audit and optionally mutate source files + the whitelist.

    Default mode is read-only.  ``--apply`` is required before any source or
    whitelist file is edited.
    """
    entries = parse_whitelist(whitelist_path)
    handled = 0
    source_edits: Set[Tuple[Path, int]] = set()
    kept: List[str] = []

    for entry in entries:
        if "symbol" not in entry:
            kept.append(entry["raw"])
            continue
        symbol = str(entry["symbol"])
        path = Path(entry["path"])
        line = int(entry["line"])

        if _matches(symbol, NOQA_PATTERNS):
            handled += 1
            if dry_run:
                if _line_needs_noqa(path, line):
                    source_edits.add((path, line))
            else:
                if _add_noqa(path, line):
                    source_edits.add((path, line))
            continue

        kept.append(entry["raw"])

    whitelist_written = False
    whitelist_header_changed = False
    if handled:
        whitelist_header_changed = _whitelist_header_would_change(whitelist_path)
        if not dry_run:
            whitelist_written = _write_whitelist_if_changed(whitelist_path, kept)

    return AuditResult(
        handled=handled,
        remaining=len(kept),
        source_edits=len(source_edits),
        whitelist_body_removed=handled,
        whitelist_written=whitelist_written,
        whitelist_header_changed=whitelist_header_changed,
        dry_run=dry_run,
    )


def _whitelist_header_would_change(path: Path) -> bool:
    if not path.exists():
        return bool(WHITELIST_HEADER)
    header: List[str] = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        if not raw.strip() or raw.lstrip().startswith("#"):
            header.append(raw.rstrip())
            continue
        break
    return header != list(WHITELIST_HEADER)


def _render_whitelist(lines: List[str]) -> str:
    body = sorted(lines, key=lambda s: s.lower())
    return "\n".join(list(WHITELIST_HEADER) + body) + "\n"


def _write_whitelist_if_changed(path: Path, lines: List[str]) -> bool:
    """Write the whitelist file only when its rendered content changed."""
    new_text = _render_whitelist(lines)
    old_text = path.read_text(encoding="utf-8") if path.exists() else ""
    if old_text == new_text:
        return False
    path.write_text(new_text, encoding="utf-8")
    return True


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Reflection-aware vulture whitelist audit.")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--apply",
        action="store_true",
        help="Edit source files and rewrite the whitelist body when needed.",
    )
    mode.add_argument(
        "--dry-run",
        action="store_true",
        help="Explicit read-only mode. This is also the default.",
    )
    parser.add_argument(
        "--whitelist",
        type=Path,
        default=DEFAULT_WHITELIST,
        help=f"Whitelist path (default: {DEFAULT_WHITELIST}).",
    )
    args = parser.parse_args(argv)

    result = audit(args.whitelist, dry_run=not args.apply)

    if result.dry_run:
        print("Read-only audit (pass --apply to edit source or whitelist files).")
        print(f"Would edit {result.source_edits} source line(s) with # noqa")
        if result.whitelist_body_removed:
            print(
                "Would update whitelist body: "
                f"remove {result.whitelist_body_removed} entr(y/ies), "
                f"{result.remaining} remaining"
            )
            print(
                "Would rewrite whitelist header: "
                f"{'yes' if result.whitelist_header_changed else 'no'}"
            )
        else:
            print("Skipped whitelist write: no body changes")
    else:
        print("Apply mode: source and whitelist edits are enabled.")
        print(f"Applied {result.source_edits} source line(s) with # noqa")
        if result.whitelist_body_removed:
            print(
                "Updated whitelist body: "
                f"removed {result.whitelist_body_removed} entr(y/ies), "
                f"{result.remaining} remaining"
            )
            print(f"Updated whitelist file: {'yes' if result.whitelist_written else 'no'}")
            print(
                "Whitelist header changed: "
                f"{'yes' if result.whitelist_written and result.whitelist_header_changed else 'no'}"
            )
        else:
            print("Skipped whitelist write: no body changes")

    if result.remaining >= 310:
        print(
            f"WARNING: whitelist still has {result.remaining} entries (target < 310).",
            file=sys.stderr,
        )
        return 1
    print(f"Whitelist is below target (< 310): {result.remaining} entries.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
