#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Recompact raw vault — 修复旧数据中的文件分片冲突。

Legacy migration only.  Current raw capture writes canonical turns to
``raw_events.db``; Obsidian raw vault markdown is generated by
``scripts/project_raw_vault.py`` via the daemon ``raw_projection`` service.

背景：
- ObsidianBackend._resolve_file_path 曾为不同 session 复用同一 part 文件名，
  导致多个 session 被追加进同一个 .md 文件，产生 8MB+ 的超大文件。
- 本脚本把现有 raw vault 中的内容按 (session, turn, 时间) 重新写入，
  利用修复后的分片逻辑生成大小均匀、按 session 隔离的文件。

行为：
1. 备份现有 .md 与 session index 到 ~/.mnemos/backups/raw-recompact-<ts>
2. 清空 raw vault 中的旧数据文件（保留 .obsidian）
3. 逐块解析并重新写入
4. 更新 sync_log.backend_uids（如果找得到对应记录）
5. 全量重建 RawIndex
"""

from __future__ import annotations

import argparse
import shutil
import sqlite3
import sys
from collections import Counter
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Tuple, cast

import yaml


def _default_raw_dir() -> Path:
    from core.config import get_config

    return Path(get_config().vault_dir("raw")).expanduser()


def _parse_blocks(text: str) -> List[Tuple[Dict[str, Any], str]]:
    """从旧的 raw .md 文件中解析出 (frontmatter_dict, body) 列表。"""
    lines = text.splitlines()
    n = len(lines)
    candidate_starts = [i for i, line in enumerate(lines) if line == "---"]

    def _is_real_block(start: int) -> bool:
        """检查从 start 开始的 --- 是否包含 session_id frontmatter。"""
        for c in candidate_starts:
            if c > start:
                fm_text = "\n".join(lines[start + 1 : c])
                return "session_id:" in fm_text
        return False

    blocks: List[Tuple[Dict[str, Any], str]] = []
    consumed = 0
    for idx, start in enumerate(candidate_starts):
        if start < consumed:
            continue
        if not _is_real_block(start):
            continue

        # 找到 frontmatter 结束符
        end = None
        for c in candidate_starts:
            if c > start:
                end = c
                break
        if end is None:
            continue

        fm_text = "\n".join(lines[start + 1 : end])
        try:
            fm = yaml.safe_load(fm_text)
        except yaml.YAMLError:
            # 不是合法 frontmatter，跳过
            continue
        if not isinstance(fm, dict) or not fm.get("session_id"):
            continue

        # 正文结束于下一个真实 block 开始之前
        body_end = n
        for c2 in candidate_starts[idx + 1 :]:
            if c2 > end and _is_real_block(c2):
                body_end = c2
                break

        body = "\n".join(lines[end + 1 : body_end])
        blocks.append((fm, body))
        consumed = body_end

    return blocks


def _fm_to_tags(fm: Dict[str, Any]) -> List[str]:
    """把 frontmatter 还原成 save() 能识别的 tags 列表。"""
    # 这些字段已经由 save() / _make_frontmatter 作为标准字段处理，
    # 这里通过 tags 传入即可保证被解析。
    standard_tag_keys = {
        "source",
        "session_id",
        "session",
        "turn",
        "content_hash",
        "model",
        "scope",
        "status",
        "content_type",
        "layer",
        "has-reasoning",
        "reasoning_capture",
        "capture_visible",
        "capture_reasoning",
        "capture_tool_results",
        "capture_truncated",
        "capture_loss",
        "skip-distill",
        "has-code",
        "has-tools",
        "task_id",
        "project",
    }
    tags: List[str] = []

    # 先把原始 tags 列表里的 key=value / 纯标签加回来
    for t in fm.get("tags") or []:
        if isinstance(t, str):
            tags.append(t)

    # 关键标准字段
    if fm.get("source"):
        tags.append(f"source={fm['source']}")
    if fm.get("session_id"):
        tags.append(f"session={fm['session_id']}")
    if fm.get("turn") is not None:
        tags.append(f"turn={fm['turn']}")
    if fm.get("content_hash"):
        tags.append(f"content_hash={fm['content_hash']}")

    # 其他需要保留的标量字段
    for key in standard_tag_keys - {"source", "session_id", "session", "turn", "content_hash"}:
        val = fm.get(key)
        if val is None:
            continue
        if isinstance(val, bool):
            tags.append(f"{key}={'true' if val else 'false'}")
        elif isinstance(val, (int, float, str)):
            tags.append(f"{key}={val}")

    # 纯标签：原始 frontmatter 中的 _plain_tags 列表
    for pt in fm.get("_plain_tags") or []:
        if isinstance(pt, str) and pt not in tags:
            tags.append(pt)

    return tags


def _fm_to_datetime(fm: Dict[str, Any]) -> datetime:
    """从 frontmatter 的 date/time 字段还原 datetime。"""
    date_str = str(fm.get("date", "1970-01-01"))
    time_str = str(fm.get("time", "0000"))
    # time 可能是 HH:MM 或 HHMM
    if ":" in time_str:
        hour, minute = time_str.split(":")
    else:
        hour = time_str[:2]
        minute = time_str[2:4]
    try:
        dt = datetime.strptime(f"{date_str} {hour}:{minute}", "%Y-%m-%d %H:%M")
    except ValueError:
        dt = datetime.strptime(date_str, "%Y-%m-%d")
    return dt


def _collect_blocks(raw_dir: Path) -> List[Tuple[Path, Dict[str, Any], str]]:
    """收集 raw_dir 下所有 .md 文件解析出的 block。"""
    all_blocks: List[Tuple[Path, Dict[str, Any], str]] = []
    md_files = sorted(raw_dir.rglob("*.md"))
    for f in md_files:
        for fm, body in _parse_blocks(f.read_text(encoding="utf-8")):
            all_blocks.append((f, fm, body))
    return all_blocks


def _compute_size_summary(md_files: List[Path]) -> Tuple[int, int, List[Path]]:
    """返回 (total_size, max_size, md_files)。"""
    sizes = [f.stat().st_size for f in md_files]
    total = sum(sizes)
    max_size = max(sizes) if sizes else 0
    return total, max_size, md_files


def _backup_raw_vault(
    raw_dir: Path, backup_dir: Path, md_files: List[Path]
) -> None:
    """备份 .md 文件与 session index 到 backup_dir。"""
    backup_dir.mkdir(parents=True, exist_ok=True)
    for f in md_files:
        rel = f.relative_to(raw_dir)
        dest = backup_dir / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(f, dest)
    for idx_file in raw_dir.rglob(".mnemos_session_index.json"):
        rel = idx_file.relative_to(raw_dir)
        dest = backup_dir / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(idx_file, dest)


def _clear_raw_vault(raw_dir: Path, md_files: List[Path]) -> None:
    """删除旧数据文件、索引和空的 YYYY/MM/DD 目录（保留 .obsidian）。"""
    for f in md_files:
        f.unlink()
    for idx_file in list(raw_dir.rglob(".mnemos_session_index.json")):
        idx_file.unlink()
    for d in sorted(raw_dir.rglob("*"), reverse=True):
        if d.is_dir() and d.name not in (".obsidian",):
            try:
                d.rmdir()
            except OSError:
                pass


def _rewrite_blocks(
    raw_dir: Path,
    all_blocks: List[Tuple[Path, Dict[str, Any], str]],
    backend_cls: Any,
) -> List[Tuple[str, str, int, str]]:
    """排序并重新写入 blocks，返回 [(agent, session_id, turn, uid), ...]。"""
    backend = backend_cls(vault_path=raw_dir)
    all_blocks.sort(
        key=lambda item: (
            _fm_to_datetime(item[1]),
            item[1].get("session_id", ""),
            int(item[1].get("turn") or 0),
        )
    )

    updated_uids: List[Tuple[str, str, int, str]] = []
    for _, fm, body in all_blocks:
        dt = _fm_to_datetime(fm)
        tags = _fm_to_tags(fm)
        session_id = str(fm.get("session_id", ""))
        turn = int(fm.get("turn") or 0)
        source = str(fm.get("source", "unknown"))
        title = f"{source}-{session_id[:8]}-turn{turn + 1}"
        results = backend.save(body, tags, title, now=dt)
        if results:
            updated_uids.append((source, session_id, turn, results[0].uid))
    return updated_uids


def _update_sync_log_uids(db_path: Path, rows: List[Tuple[str, str, int, str]]) -> int:
    """批量更新 sync_log.backend_uids。rows: [(agent, session_id, turn, uid), ...]"""
    if not db_path.exists() or not rows:
        return 0
    conn = sqlite3.connect(str(db_path))
    try:
        cursor = conn.cursor()
        updated = 0
        for agent, session_id, turn, uid in rows:
            cursor.execute(
                "UPDATE sync_log SET backend_uids = ? WHERE agent_name = ? AND session_id = ? AND turn_number = ?",  # noqa: E501
                (uid, agent, session_id, turn),
            )
            updated += cursor.rowcount
        conn.commit()
        return updated
    finally:
        conn.close()


def _rebuild_raw_index(raw_dir: Path, index_cls: Any) -> Dict[str, int]:
    """全量重建 RawIndex 并返回统计信息。"""
    idx = index_cls(raw_dir=raw_dir)
    stats = idx.sync_index(force_full=True)
    idx.close()
    return cast(Dict[str, int], stats)


def _print_recompact_report(
    raw_dir: Path,
    turn_count: int,
    new_files: List[Path],
    threshold: int,
    backup_dir: Path,
) -> None:
    """打印 recompact 完成报告（MB/KB 单位）。"""
    new_sizes = [f.stat().st_size for f in new_files]
    max_size = max(new_sizes) if new_sizes else 0
    total_size = sum(new_sizes)
    oversized = [f for f in new_files if f.stat().st_size > threshold]
    print()
    print("=== recompact 完成 ===")
    print(f"写入 turn 数: {turn_count}")
    print(f"生成文件数: {len(new_files)}")
    print(f"总大小: {total_size / 1024 / 1024:.2f} MB")
    print(f"最大文件: {max_size / 1024 / 1024:.2f} MB")
    print(f"超阈值(>{threshold/1024:.0f}KB)文件数: {len(oversized)}")
    if oversized:
        print("超大文件:")
        for f in oversized:
            print(f"  {f.relative_to(raw_dir)}: {f.stat().st_size / 1024:.1f} KB")
    print(f"备份位置: {backup_dir}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Recompact Obsidian raw vault")
    parser.add_argument(
        "--raw-dir",
        default=None,
        help="raw vault 路径；未指定时读取配置中的 vaults.raw.path",
    )
    parser.add_argument("--dry-run", action="store_true", help="只统计不写入")
    args = parser.parse_args()

    raw_dir = Path(args.raw_dir).expanduser() if args.raw_dir else _default_raw_dir()
    if not raw_dir.exists():
        print(f"raw vault 不存在: {raw_dir}")
        return 1

    md_files = sorted(raw_dir.rglob("*.md"))
    print(f"发现 {len(md_files)} 个 .md 文件")

    all_blocks = _collect_blocks(raw_dir)
    print(f"解析出 {len(all_blocks)} 个 turn block")
    if not all_blocks:
        print("没有需要处理的内容")
        return 0

    session_counts = Counter(b[1].get("session_id") for b in all_blocks)
    print(f"涉及 {len(session_counts)} 个 session")

    _, max_old_size, _ = _compute_size_summary(md_files)
    total_old_size = sum(f.stat().st_size for f in md_files)
    print(
        f"当前最大文件: {max_old_size / 1024 / 1024:.2f} MB, 总大小: {total_old_size / 1024 / 1024:.2f} MB"
    )

    if args.dry_run:
        return 0

    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_dir = Path.home() / ".mnemos" / "backups" / f"raw-recompact-{ts}"
    _backup_raw_vault(raw_dir, backup_dir, md_files)
    print(f"备份旧文件到: {backup_dir}")

    _clear_raw_vault(raw_dir, md_files)
    print("删除旧数据文件...")

    print("重新写入 blocks...")
    sys.path.insert(0, str(Path(__file__).parent.parent))
    from integrations.backends.obsidian_backend import ObsidianBackend

    updated_uids = _rewrite_blocks(raw_dir, all_blocks, ObsidianBackend)

    from core.config import get_config

    cfg = get_config()
    sync_db = cfg.database_dir / "sync_log.db"
    updated = _update_sync_log_uids(sync_db, updated_uids)
    print(f"更新 sync_log.backend_uids: {updated}/{len(updated_uids)}")

    print("重建 RawIndex...")
    from core.app.raw_search import RawIndex

    stats = _rebuild_raw_index(raw_dir, RawIndex)
    print(
        f"RawIndex: indexed={stats['indexed']}, removed={stats['removed']}, skipped={stats['skipped']}"  # noqa: E501
    )

    new_files = sorted(raw_dir.rglob("*.md"))
    backend = ObsidianBackend(vault_path=raw_dir)
    _print_recompact_report(
        raw_dir=raw_dir,
        turn_count=len(all_blocks),
        new_files=new_files,
        threshold=backend.daily_size_threshold,
        backup_dir=backup_dir,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
