"""Tests for the vulture dead-code check wrapper."""

from __future__ import annotations

import sys

from scripts import audit_vulture_whitelist
from scripts import run_vulture_check


def _configure_vulture_audit_project(monkeypatch, tmp_path):
    monkeypatch.setattr(audit_vulture_whitelist, "PROJECT_ROOT", tmp_path)
    monkeypatch.setattr(
        audit_vulture_whitelist,
        "DEFAULT_WHITELIST",
        tmp_path / "vulture_whitelist.py",
    )


def test_vulture_audit_default_is_read_only(monkeypatch, tmp_path, capsys):
    _configure_vulture_audit_project(monkeypatch, tmp_path)
    source = tmp_path / "module.py"
    source.write_text("row.row_factory = dict\n", encoding="utf-8")
    whitelist = tmp_path / "vulture_whitelist.py"
    original = (
        "# Review contract: keep this header\n"
        "\n"
        "_.row_factory  # unused attribute (module.py:1)\n"
    )
    whitelist.write_text(original, encoding="utf-8")

    assert audit_vulture_whitelist.main(["--whitelist", str(whitelist)]) == 0

    assert source.read_text(encoding="utf-8") == "row.row_factory = dict\n"
    assert whitelist.read_text(encoding="utf-8") == original
    captured = capsys.readouterr()
    assert "Read-only audit" in captured.out
    assert "Would edit 1 source line(s) with # noqa" in captured.out
    assert "Would update whitelist body: remove 1 entr(y/ies)" in captured.out


def test_vulture_audit_apply_does_not_rewrite_header_without_body_changes(
    monkeypatch, tmp_path, capsys
):
    _configure_vulture_audit_project(monkeypatch, tmp_path)
    whitelist = tmp_path / "vulture_whitelist.py"
    original = (
        "# Review contract: keep this header\n"
        "\n"
        "live_symbol  # unused function (module.py:1)\n"
    )
    whitelist.write_text(original, encoding="utf-8")

    assert audit_vulture_whitelist.main(["--apply", "--whitelist", str(whitelist)]) == 0

    assert whitelist.read_text(encoding="utf-8") == original
    captured = capsys.readouterr()
    assert "Skipped whitelist write: no body changes" in captured.out


def test_vulture_audit_apply_updates_source_and_whitelist(monkeypatch, tmp_path, capsys):
    _configure_vulture_audit_project(monkeypatch, tmp_path)
    source = tmp_path / "module.py"
    source.write_text("row.row_factory = dict\n", encoding="utf-8")
    whitelist = tmp_path / "vulture_whitelist.py"
    whitelist.write_text(
        "# Review contract: keep this header\n"
        "\n"
        "_.row_factory  # unused attribute (module.py:1)\n",
        encoding="utf-8",
    )

    assert audit_vulture_whitelist.main(["--apply", "--whitelist", str(whitelist)]) == 0

    assert source.read_text(encoding="utf-8") == "row.row_factory = dict  # noqa\n"
    whitelist_text = whitelist.read_text(encoding="utf-8")
    assert "_.row_factory" not in whitelist_text
    assert "# Auto-generated by scripts/audit_vulture_whitelist.py" in whitelist_text
    captured = capsys.readouterr()
    assert "Applied 1 source line(s) with # noqa" in captured.out
    assert "Updated whitelist file: yes" in captured.out


def test_count_whitelist_entries_ignores_comments(tmp_path):
    whitelist = tmp_path / "vulture_whitelist.py"
    whitelist.write_text(
        "# header\n\nfoo  # unused function (x.py:1)\nbar  # unused method (y.py:2)\n",
        encoding="utf-8",
    )

    assert run_vulture_check.count_whitelist_entries(whitelist) == 2


def test_missing_vulture_returns_install_hint(monkeypatch, tmp_path, capsys):
    whitelist = tmp_path / "vulture_whitelist.py"
    whitelist.write_text("", encoding="utf-8")
    monkeypatch.setattr(run_vulture_check, "vulture_available", lambda: False)

    assert run_vulture_check.main(["--repo-root", str(tmp_path), "--whitelist", str(whitelist)]) == 2

    captured = capsys.readouterr()
    assert "python3 -m pip install -e '.[dev]'" in captured.err


def test_budget_only_fails_when_whitelist_exceeds_budget(tmp_path, capsys):
    whitelist = tmp_path / "vulture_whitelist.py"
    whitelist.write_text("foo  # unused function (x.py:1)\n", encoding="utf-8")

    assert (
        run_vulture_check.main(
            ["--repo-root", str(tmp_path), "--whitelist", str(whitelist), "--budget", "0"]
        )
        == 1
    )

    captured = capsys.readouterr()
    assert "budget exceeded" in captured.err


def test_build_vulture_command_uses_python_module(tmp_path):
    command = run_vulture_check.build_vulture_command(
        repo_root=tmp_path,
        whitelist=tmp_path / "vulture_whitelist.py",
        min_confidence=80,
    )

    assert command[:3] == [sys.executable, "-m", "vulture"]
    assert command[-2:] == ["--min-confidence", "80"]


def test_main_invokes_vulture_when_available(monkeypatch, tmp_path):
    whitelist = tmp_path / "vulture_whitelist.py"
    whitelist.write_text("", encoding="utf-8")
    calls = []
    monkeypatch.setattr(run_vulture_check, "vulture_available", lambda: True)
    monkeypatch.setattr(
        run_vulture_check.subprocess,
        "call",
        lambda command, cwd=None: calls.append((command, cwd)) or 7,
    )

    assert run_vulture_check.main(["--repo-root", str(tmp_path), "--whitelist", str(whitelist)]) == 7

    assert calls
    assert calls[0][0][0:3] == [sys.executable, "-m", "vulture"]
    assert calls[0][1] == tmp_path
